services:
 db:
    image: mysql:8.4
    container_name: mysql_mantequilla
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_datos:/var/lib/mysql

volumes:
  mysql_datos:
